import type { MeetingRecord } from "@/lib/meetings/repository"

export const DEMO_MEETINGS: MeetingRecord[] = [
  {
    id: "meet_google_workspace",
    title: "Q2 Acquisition Review",
    source: "google_meet",
    language: "en",
    status: "completed",
    retention: "audio",
    startedAt: "2026-04-24T10:30:00.000Z",
    participants: ["Ran Nahmany", "Asaf Ronen", "Leandro Silva", "Yael Ben-David"],
    tags: ["real-estate", "finance", "follow-up-needed", "english", "mixed-language"],
    summary: {
      overview:
        "We reviewed 3 new acquisition opportunities in Lisbon and Porto, discussed financing options with our lender, and agreed on due diligence priorities. Next steps and responsibilities were assigned for underwriting, legal review, and site visits.",
      decisions: [
        "Proceed with detailed due diligence on Lisboa Riverside Project.",
        "Set target IRR >= 17% for all Q2 acquisitions.",
        "Engage legal counsel for SPA review by April 30.",
      ],
      actionItems: [
        {
          id: "act_google_1",
          title: "Underwrite Lisboa Riverside Project",
          owner: "Ran Nahmany",
          status: "open",
          priority: "high",
          dueDate: "Apr 28",
          confidence: 0.92,
        },
        {
          id: "act_google_2",
          title: "Schedule site visit - Porto Industrial",
          owner: "Asaf Ronen",
          status: "open",
          priority: "normal",
          dueDate: "Apr 29",
          confidence: 0.9,
        },
        {
          id: "act_google_3",
          title: "Finalize lender term sheet",
          owner: "Leandro Silva",
          status: "open",
          priority: "high",
          dueDate: "May 1",
          confidence: 0.88,
        },
        {
          id: "act_google_4",
          title: "Draft LOI for target #3",
          owner: "Yael Ben-David",
          status: "open",
          priority: "normal",
          dueDate: "May 3",
          confidence: 0.86,
        },
      ],
    },
    transcript: [
      {
        id: "seg_google_1",
        speaker: "Ran Nahmany",
        startMs: 0,
        endMs: 12340,
        text: "If the IRR is below 17%, we should walk away.",
        confidence: 0.95,
      },
      {
        id: "seg_google_2",
        speaker: "Leandro Silva",
        startMs: 28841,
        endMs: 36400,
        text: "The lender can move faster if we provide the updated NOI model.",
        confidence: 0.92,
      },
    ],
  },
  {
    id: "meet_realizeos",
    title: "Project Horizon Standup",
    source: "desktop_recorder",
    language: "he",
    status: "indexing",
    retention: "audio",
    startedAt: "2026-04-24T09:00:00.000Z",
    participants: ["Ran", "Ops agent", "Maya"],
    tags: ["operations", "technical"],
    summary: {
      overview:
        "RealizeOS should receive compact meeting memory packets with decisions, action items, owners, and source links.",
      decisions: ["Start with outbound REST webhooks, then add MCP tools."],
      actionItems: [
        {
          id: "act_realizeos_1",
          title: "Define the RealizeOS meeting-context payload",
          owner: "Ran",
          status: "open",
        },
      ],
    },
    transcript: [
      {
        id: "seg_realizeos_1",
        speaker: "Ran",
        startMs: 0,
        endMs: 4200,
        text: "We need RealizeOS to receive context from every meeting.",
      },
    ],
  },
  {
    id: "meet_hebrew_quality",
    title: "Client Follow-up - Leo Co.",
    source: "pwa_recorder",
    language: "he",
    status: "summarizing",
    retention: "audio",
    startedAt: "2026-04-23T11:00:00.000Z",
    participants: ["Ran", "Noa"],
    tags: ["sales", "follow-up-needed", "finance", "hebrew"],
    summary: {
      overview:
        "Hebrew output should preserve names, jargon, dates, responsibility, and uncertainty markers.",
      decisions: ["Escalate low-confidence Hebrew chunks to a stronger API model."],
      actionItems: [
        {
          id: "act_hebrew_1",
          title: "Build a Hebrew regression sample set",
          owner: "Noa",
          status: "open",
        },
      ],
    },
    transcript: [
      {
        id: "seg_hebrew_1",
        speaker: "Noa",
        startMs: 0,
        endMs: 6100,
        text: "Accuracy in Hebrew matters more than saving a few cents on difficult chunks.",
      },
    ],
  },
  {
    id: "meet_strategy_recording",
    title: "Strategy Session Recording",
    source: "upload",
    language: "en",
    status: "completed",
    retention: "audio",
    startedAt: "2026-04-23T08:15:00.000Z",
    participants: ["Ran", "Maya", "Finance"],
    tags: ["operations", "product"],
    summary: {
      overview:
        "The team reviewed planning assumptions and prioritized imported recordings, Workspace context, and RealizeOS exports.",
      decisions: ["Use imported recordings as the fastest proof path."],
      actionItems: [
        {
          id: "act_strategy_1",
          title: "Review imported Drive recording quality",
          owner: "Maya",
          status: "open",
        },
      ],
    },
    transcript: [
      {
        id: "seg_strategy_1",
        speaker: "Ran",
        startMs: 0,
        endMs: 4200,
        text: "The first version should feel operational and reliable.",
      },
    ],
  },
  {
    id: "meet_product_roadmap",
    title: "Product Roadmap Sync",
    source: "google_meet",
    language: "en",
    status: "scheduled",
    retention: "audio",
    startedAt: "2026-04-22T13:00:00.000Z",
    participants: ["Ran", "Product", "Ops"],
    tags: ["product", "technical"],
    summary: {
      overview: "Roadmap sync scheduled from Google Calendar.",
      decisions: [],
      actionItems: [],
    },
    transcript: [],
  },
  {
    id: "meet_weekly_ops",
    title: "Weekly Ops Review",
    source: "google_meet",
    language: "en",
    status: "completed",
    retention: "audio",
    startedAt: "2026-04-22T09:00:00.000Z",
    participants: ["Ran", "Operations"],
    tags: ["operations"],
    summary: {
      overview: "Operations review focused on follow-ups, automations, and owner accountability.",
      decisions: ["Keep action owner extraction visible in the meeting table."],
      actionItems: [],
    },
    transcript: [
      {
        id: "seg_ops_1",
        speaker: "Operations",
        startMs: 0,
        endMs: 5000,
        text: "Every action item needs a clear owner and source quote.",
      },
    ],
  },
  {
    id: "meet_investor_update",
    title: "Investor Update Call",
    source: "pwa_recorder",
    language: "en",
    status: "completed",
    retention: "audio",
    startedAt: "2026-04-21T15:00:00.000Z",
    participants: ["Ran", "Investor"],
    tags: ["finance", "sales"],
    summary: {
      overview: "Investor call covered acquisition pipeline, financing status, and next reporting cadence.",
      decisions: ["Send concise weekly follow-up notes."],
      actionItems: [],
    },
    transcript: [
      {
        id: "seg_investor_1",
        speaker: "Investor",
        startMs: 0,
        endMs: 4300,
        text: "A short weekly update is enough if the numbers are clear.",
      },
    ],
  },
]
